### ISSUE TITLE
gen_cfg.idc可以开源么？

### ISSUE THREAD

**Issue by 3wh1te** [yuriufo/DataCon2020#1]
谢谢

**Comment by yuriufo** [comment]
已上传至[old\cg\gen_fcg.idc](https://github.com/yuriufo/DataCon2020/blob/master/old/cg/gen_fcg.idc)

**Comment by 3wh1te** [comment]
Thx！！！！！！！

**Comment by 3wh1te** [comment]
这个脚本我试了一下Ember的数据，并不是所有的可执行文件都可以生成gdl。哪里出了什么问题么？

**Comment by yuriufo** [comment]
我认为这和样本的加壳混淆或IDA Pro反汇编有很大的关系。
你可以把无法生成gdl的文件拿出来，用IDA Pro单独分析它们，看是否有文件格式解析失败、反汇编后识别不出代码段函数等问题。
这些问题要么是因为IDA Pro分析失败，要么就是缺少函数结点。

**Comment by 3wh1te** [comment]
所以这些用call graph训练的时候要抛弃这些数据，做分析的时候这些要单独分析？

**Comment by yuriufo** [comment]
对于单模型的话可能确实得这么做

**Comment by 3wh1te** [comment]
OK

**Comment by 3wh1te** [comment]
请问一下，IDA pro在服务器上部署的还是在本地机跑的，我这边Ubuntu服务器IDAfree和 IDA pro有出问题。

**Comment by yuriufo** [comment]
我用的是linux的IDA Pro 7.4，你可以在你的ubuntu下用idat64打开一个文件分析，然后导入脚本文件查看输出来检查错误原因，导入脚本操作如下。

![图片](https://user-images.githubusercontent.com/30290025/102998862-fdacbd80-4562-11eb-8672-225d6ca86048.png)

**Comment by 3wh1te** [comment]
ida可以分享一下么

**Comment by yuriufo** [comment]
这是购买带license的，抱歉不能分享。

**Comment by 3wh1te** [comment]
你的服务器是装了图形化界面么，我的好像都是因为qt的原因无法运行。

**Comment by yuriufo** [comment]
没装，我这个是解压后开箱即用的，可能缺了qt的库

**Comment by 3wh1te** [comment]
IDA pro Linux版本在哪可以购买，我看官网只有freeware有Linux版本，Linux for IDA pro也只有6.4 32位的，freeware不能做批处理……

**Comment by yuriufo** [comment]
https://www.hex-rays.com/cgi-bin/quote.cgi
